language: clojure

sudo: required

services:
  - docker

jdk:
  - oraclejdk8

script:
  - lein test
  - lein uberjar
  - docker build -t axeclbr/travisprobe .
  - docker run -d -p 127.0.0.1:80:3000 --name app axeclbr/travisprobe
  - sleep 10
  - curl -I localhost || exit 1

after_success:
  - lein cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
