language: clojure

jdk:
  - oraclejdk8

after_success:
  - lein cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json

sudo: required

services:
  - docker

before_install:
  - lein uberjar
  - docker build -t axeclbr/travisprobe .
  - docker run -d -p 127.0.0.1:3000 --name app axeclbr/travisprobe
  - sleep 10

script:
  - curl -I localhost || exit 1
